using System;

namespace COIS_3320_Lab_2
{
    // Class to generate values from a gaussian distribution
    static class Gaussian
    {
        private static double backup;           // Stores second value generated by algorithm
        private static bool isBackup = false;   // Checks if second value has been used
        
        // Generates and returns values from a gaussian distribution with given mean and standard deviation
        // Parameters:
        //      Random rnd - used to generate random values
        //      mu - mean
        //      sigma - standard deviation
        public static double Generate(Random rnd, double mu, double sigma)
        {
            // Checks if backup value has been used and if not, returns it with given mean and standard deviation
            if (isBackup)
            {
                isBackup = !isBackup;
                return mu + sigma * backup;
            }
            // Otherwise generates 2 values from gaussian distribution, stores one, and returns the other with given mean and standard deviation
            double x, y, rsq, f;
            do
            {
                x = 2.0 * rnd.NextDouble() - 1.0;
                y = 2.0 * rnd.NextDouble() - 1.0;
                rsq = x * x + y * y;
            } while (rsq >= 1 || rsq == 0);
            f = Math.Sqrt(-2.0 * Math.Log(rsq) / rsq);
            backup = y * f;
            return mu + sigma * x * f;
        }
    }
}
